### ISSUE TITLE
include error

### ISSUE THREAD

**Issue by Pidermen** [insggg/cs2_external_internal#15]
I tried to include freetype in the project and wrote freetype/include in the project itself and got more than 61 errors (p.s i use .sln).
![Screenshot_11](https://github.com/insggg/cs2_external_internal/assets/160334012/3eb165d7-7df6-48a9-86a4-d3bf46610c05)

**Comment by Pidermen** [comment]
сука, чит работает только на -insecure, а самому софту глобал апдейт надо нахуй, даже с изменными оффсетами не работает 60% софта, вх кривое пизда

**Comment by insggg** [comment]
ну, что бы обновить мозг нужен, увы =(
